### ISSUE TITLE
Can't deploy single node - failing to connect to redis

### ISSUE THREAD

**Issue by apolishch** [ritual-net/infernet-deploy#2]
Can't run node following (single node) instructions:

https://docs.ritual.net/infernet/node/deployment

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 264, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 265, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 627, in _connect
    raise err
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 615, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/orchestration/store.py", line 119, in __init__
    self._completed.ping()
  File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1216, in ping
    return self.execute_command("PING", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 533, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1086, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 270, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/main.py", line 182, in <module>
    on_startup()
  File "/app/src/main.py", line 53, in on_startup
    store = DataStore(config["redis"]["host"], config["redis"]["port"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/orchestration/store.py", line 125, in __init__
    raise RuntimeError(
RuntimeError: Could not connect to Redis. Please check your configuration.
```

**Comment by stelios-ritual** [comment]
@apolishch What is your redis configuration in `config.json`?

**Comment by apolishch** [comment]
@stelios-ritual 

# Listen on localhost
bind 127.0.0.1 ::1

# Loglevel
loglevel notice

# Path to log file
logfile /var/log/redis/redis-server.log

# Number of databases
databases 2

# Working directory
dir /var/lib/redis

# Save to disk every 60 seconds if at least 1 change
save 60 1

# Maximum memory before eviction starts
maxmemory 1gb

# Eviction policy
maxmemory-policy allkeys-lru

**Comment by apolishch** [comment]
@stelios-ritual 

1) Herp derp
  "redis": {
    "host": "localhost",
    "port": 6379
  },

2) via docker compose.

**Comment by stelios-ritual** [comment]
Since the node is running inside a container, your host's `localhost` is not a accessible as "localhost" from within that container. That's why the node can't connect to redis.

Assuming you have not changed the docker compose file, i.e. the name of the redis service is still "redis" in `docker-compose.yaml`, changing to the following should fix it:

```json
"redis": {
  "host": "redis",
  "port": 6379
},

```
